language: java
script:
 - cd clouddesigner/org.occiware.clouddesigner.parent && mvn clean verify 
 - curl -T /home/travis/build/wpiers/ecore/clouddesigner/org.occiware.clouddesigner.product/target/products/org.occiware.clouddesigner.product-win32.win32.x86.zip -uwpiers:$KEY https://api.bintray.com/content/wpiers/generic/CloudDesigner/$TRAVIS_JOB_NUMBER/CloudDesigner.win32.x86.zip
 - curl -XPOST -uwpiers:$KEY https://api.bintray.com/content/wpiers/generic/CloudDesigner/$TRAVIS_JOB_NUMBER/publish

